"""
Manual validation script for M1 — programmatic score generation.

Creates a simple 8-measure C-major scale exercise at 60 BPM, writes it as
both MusicXML and MIDI, then prints instructions for external validation.

Usage:
    python test/m1/generate_manual_score.py

Outputs (written next to this script):
    test/m1/manual_score.musicxml  — open in MuseScore to verify notation
    test/m1/manual_score.mid       — play back with timidity, e.g.:
                                     timidity test/m1/manual_score.mid
"""

from __future__ import annotations

import pathlib
import sys
import tempfile

# Allow running from the repo root without installing the package.
_REPO_ROOT = pathlib.Path(__file__).parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

import music21.stream
import music21.note
import music21.meter
import music21.key
import music21.tempo
import music21.dynamics
import music21.metadata
import music21.instrument
from music21.midi.translate import music21ObjectToMidiFile

from core.io.musicxml_io import save_musicxml
from core.io.midi_io import load_midi, save_midi

_TEMPO_BPM = 60
_TEMPO_US = 1_000_000  # microseconds per beat at 60 BPM

OUT_DIR = pathlib.Path(__file__).parent
MUSICXML_OUT = OUT_DIR / "manual_score.musicxml"
MIDI_OUT = OUT_DIR / "manual_score.mid"


# ---------------------------------------------------------------------------
# Score definition
#
# 8 measures of 4/4, C major, 60 BPM.
# Each measure presents one step of a two-octave C-major scale (C4–C6)
# using quarter notes, with a simple dynamic arc: mp → mf → f → mf → mp.
# Measure 8 ends on a whole note C4.
# ---------------------------------------------------------------------------

def build_score() -> music21.stream.Score:
    score = music21.stream.Score()
    score.metadata = music21.metadata.Metadata()
    score.metadata.title = "M1 Manual Validation — C Major Exercise"
    score.metadata.composer = "Generated by generate_manual_score.py"

    part = music21.stream.Part()
    part.insert(0, music21.instrument.Piano())

    # Global markings at the very start (inserted into the part, offset 0)
    part.insert(0, music21.tempo.MetronomeMark(number=_TEMPO_BPM))
    part.insert(0, music21.key.Key("C"))
    part.insert(0, music21.meter.TimeSignature("4/4"))

    # ---------------------------------------------------------------------------
    # Note material: ascending C major scale C4–B5 across 7 measures (4 notes
    # each), then a final whole-note C4 in measure 8.
    # ---------------------------------------------------------------------------
    scale_pitches = [
        "C4", "D4", "E4", "F4",   # measure 1
        "G4", "A4", "B4", "C5",   # measure 2
        "D5", "E5", "F5", "G5",   # measure 3
        "A5", "B5", "C6", "B5",   # measure 4
        "A5", "G5", "F5", "E5",   # measure 5  (descending)
        "D5", "C5", "B4", "A4",   # measure 6
        "G4", "F4", "E4", "D4",   # measure 7
    ]

    # Dynamics per measure (index 0 = measure 1)
    dynamics_map = {
        0: "mp",
        1: "mf",
        2: "f",
        3: "f",
        4: "mf",
        5: "mp",
        6: "p",
    }

    pitch_idx = 0
    for measure_num in range(1, 9):
        measure = music21.stream.Measure(number=measure_num)

        if measure_num < 8:
            # Insert dynamic at the start of the measure
            dyn_value = dynamics_map.get(measure_num - 1, "mp")
            measure.insert(0, music21.dynamics.Dynamic(dyn_value))

            # 4 quarter notes
            for _ in range(4):
                n = music21.note.Note(scale_pitches[pitch_idx], quarterLength=1)
                measure.append(n)
                pitch_idx += 1
        else:
            # Measure 8: whole note C4 with a pp dynamic
            measure.insert(0, music21.dynamics.Dynamic("pp"))
            n = music21.note.Note("C4", quarterLength=4)
            measure.append(n)

        part.append(measure)

    score.append(part)
    return score


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("Building 8-measure C-major exercise score...")
    score = build_score()

    # --- MusicXML ---
    save_musicxml(score, MUSICXML_OUT)
    print(f"  MusicXML written → {MUSICXML_OUT}")
    print("  Open in MuseScore: File > Open > select manual_score.musicxml")
    print("  Verify: 8 measures, 4/4, C major, ascending/descending scale, dynamics arc")

    # --- MIDI ---
    # Get ticks_per_beat directly from music21 without reading a temp file.
    # music21 uses a non-standard resolution (10080 ticks/beat); we must pass
    # it explicitly to save_midi so tick values are written at the same scale
    # they were loaded — otherwise the tempo would be silently wrong.
    ticks_per_beat = music21ObjectToMidiFile(score).ticksPerQuarterNote

    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as tmp:
        tmp_path = pathlib.Path(tmp.name)
    score.write("midi", fp=str(tmp_path))
    events, _ = load_midi(tmp_path)
    tmp_path.unlink(missing_ok=True)

    save_midi(events, MIDI_OUT, ticks_per_beat=ticks_per_beat, tempo=_TEMPO_US)

    print(f"\n  MIDI written    → {MIDI_OUT}")
    print("  Play back with timidity:")
    print(f"    timidity {MIDI_OUT}")
    print("\nManual validation complete. Check outputs above.")

    # Summary of what was generated
    note_on_count = sum(1 for e in events if e.type == "note_on")
    print(f"\nEvent summary from MIDI round-trip:")
    print(f"  ticks_per_beat      : {ticks_per_beat}")
    print(f"  Total events parsed : {len(events)}")
    print(f"  note_on events      : {note_on_count}")


if __name__ == "__main__":
    main()
