name: midi_keyboard_monitor_app
description: Flutter client for MIDI Keyboard Monitor (velocity visualization)
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_reactive_ble: ^5.0.2
#  permission_handler: ^10.4.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
